### PR TITLE
Test

### PR DESCRIPTION
**Pull request by twedl**
Test some shib. Hmm. But you haven't pushed your latest version. Well I hope this works anyway.

### CODE REVIEW

**Comment by Bcohn** [comment]
what are you testing? i added residuals and now have this message 

"This branch has conflicts that must be resolved
Use the command line to resolve conflicts before continuing.
 Merge pull request"

**Comment by twedl** [comment]
i added a comment "hi brent!"

**Comment by Bcohn** [comment]
lol,you have to merge it with my branch then i think.

**Comment by twedl** [comment]
I don't have permission. I was trying to figure out how to fork-pr

**Comment by Bcohn** [comment]
oh, i mean update your fork to the master then merge you updates?

**Comment by twedl** [comment]
again?

**Comment by Bcohn** [comment]
yea because i updated the master with the residuals after you tried to
update.

**Pull request closed without merging**
